import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { BodyWrapper } from "@/components/body-wrapper";
import { cn } from "@/lib/utils";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900`}>
        <BodyWrapper>{children}</BodyWrapper>
      </body>
    </html>
  );
}
